version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django:
    image: ${DOCKER_IMAGE_BACKEND:-${DOCKER_USERNAME}/voucher-tracker-backend:latest}
    restart: unless-stopped
    volumes:
      - production_django_media:/app/backend/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    environment:
      - DJANGO_ALLOWED_HOSTS=*
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: backend_production_postgres
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: docker.io/redis:6
    restart: unless-stopped

  nginx:
    image: ${DOCKER_IMAGE_NGINX:-${DOCKER_USERNAME}/voucher-tracker-nginx:latest}
    restart: unless-stopped
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    ports:
      - "80:80" # Exposed for Cosmos to route to (or map to random host port)
