version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django:
    # 1. UPDATED: Hardcoded your image so you don't need extra env vars
    image: vaibhav198/voucher-tracker-backend:latest
    restart: unless-stopped
    volumes:
      - production_django_media:/app/backend/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8050
    command: /start

  postgres:
    # 2. UPDATED: Removed 'build'. Used standard image so you don't need source code.
    image: postgres:16
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:6
    restart: unless-stopped

  nginx:
    # 3. UPDATED: Hardcoded image name
    image: vaibhav198/voucher-tracker-nginx:latest
    restart: unless-stopped
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    # 4. UPDATED: Fixed duplicate keys and Port Conflict
    ports:
      - "8050:80"  # Map Host 8050 -> Container 80. Cosmos will talk to 8050.

  telegram_bot:
    image: vaibhav198/voucher-tracker-backend:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: python manage.py run_telegram_bot
